# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Full-Stack Quantum Computation"
title_separator: "|"
subtitle: "Community-driven, open-source education resources"
name: People Interested in Quantum Universal Education
email: "lia@fullstackquantumcomputation.tech"
description: >- # this means to ignore newlines until "baseurl:"
  "Welcome to this community-driven, open-source educational website for learning about all aspects of quantum computing across the full stack, from hardware to algorithms to everything in between and adjacent!  Whether you are new to quantum science, filling in gaps in your foundation of knowledge, or supplementing a course you are taking, our goal is to help you learn based on your interests and background knowledge.  We are always open to recommendations and contributions from the quantum computing community."
url: "https://fullstackquantumcomputation.tech"
  #twitter_username: username
github_username: "Quantum-Universal-Education"
repository: "Quantum-Universal-Education/Quantum-Universal-Education.github.io"
minimal_mistakes_skin: dirt
search: true
logo: "/assets/images/FSQC-small.png"
# Open Graph default image
og_image: "/assets/images/FSQC-small.png"
 
# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache


    #author:
    #  name   : "First Lastname"
    #  avatar : "/assets/images/bio-photo.jpg"
    #  bio    : "My awesome biography constrained to a sentence or two goes here."
    #  links:
    #    - label: "Website"
    #      icon: "fas fa-fw fa-link"
    #      url: "https://"
    #    - label: "Twitter"
    #      icon: "fab fa-fw fa-twitter-square"
    #      url: "https://twitter.com/"
    #    - label: "GitHub"
    #      icon: "fab fa-fw fa-github"
    #      url: "https://github.com/"
    #    - label: "Instagram"
    #      icon: "fab fa-fw fa-instagram"
    #      url: "https://instagram.com/"


footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Quantum-Universal-Education/Quantum-Universal-Education.github.io"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/company/quantum-universal-education/"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/QuantumUniversalEducation"
    #    - label: "Twitter"
    #      icon: "fab fa-fw fa-twitter-square"
    #      url: "https://twitter.com/"
    #    - label: "Instagram"
    #      icon: "fab fa-fw fa-instagram"
    #      url: "https://instagram.com/"

defaults:
 # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
kramdown:
  math_engine: katex
